version: '3'

services:
  slave1:
    image: ankitkamboj/hadoop-ha
    entrypoint:
      - /root/scripts/journal_entrypoint.sh
      - -d
      - "1"

  slave2:
    image: ankitkamboj/hadoop-ha
    entrypoint: 
      - /root/scripts/journal_entrypoint.sh
      - -d
      - "2"
    depends_on: 
      - "slave1"

  slave3:
    image: ankitkamboj/hadoop-ha
    entrypoint: 
      - /root/scripts/journal_entrypoint.sh
      - -d
      - "3"
    depends_on: 
      - "slave1"

  master:
    image: ankitkamboj/hadoop-ha
    entrypoint: 
      - /root/scripts/nm_entrypoint.sh
      - -d
    depends_on: 
      - "slave3"
    ports:
      - "8088:8088"
      - "50070:50070"
      - "2122:2122"

  smaster:
    image: ankitkamboj/hadoop-ha
    entrypoint: 
      - /root/scripts/stnn_entrypoint.sh
      - -d
    depends_on: 
      - "master"
      - "slave1"
      - "slave2"
      - "slave3"
    ports:
      - "50091:50091"
      - "50090:50090" 
      - "8098:8088"
      - "50080:50070"
