version: '2'

services:
  slave1:
    build: ./namenode/
    entrypoint: 
      - /root/scripts/sl_entrypoint.sh
      - -d
    container_name: "slave1"
    
  slave2:
    build: ./namenode/
    entrypoint: 
      - /root/scripts/slave_entrypoint.sh
      - -d
    container_name: "slave2"

  master:
    build: ./namenode/
    entrypoint: 
      - /root/scripts/nm_entrypoint.sh
      - -d
    depends_on: 
      - "slave1"
    ports:
      - "8088:8088"
      - "50070:50070"
      - "2122:2122"
    container_name: "master"
  
  smaster:
    build: ./namenode/
    entrypoint: 
      - /root/scripts/stnn_entrypoint.sh
      - -d
    depends_on: 
      - "master"
    ports:
      - "50091:50091"
      - "50090:50090" 
      - "8098:8088"
      - "50080:50070"
    container_name: "smaster"