version: '2'

services:
  master:
    build: ./namenode/
    ports:
      - "8088:8088"
      - "50070:50070"
      - "2122:2122"
    container_name: "master"
  smaster:
    build: ./namenode/
    depends_on: ["master"]
    ports:
      - "50091:50091"
      - "50090:50090"
    container_name: "smaster"